DGU-GraduationDesign-Babhangongi/Dongguk-Air-in-Seoul

package-lock.json
package.json
src/components/common/Header/Login_Header.css
src/components/common/Header/Login_Header.js
src/pages/Login/Login.css
src/pages/Login/Login.js

1. 로그인 전 회원가입과 로그인 페이지에서 볼 수 있는 헤더 생성 1_2. ../Header/Login_Header.js, Login_Header.css
2. ../Header/Header.js와 .css를 가져왔는데 비율에 실패함
3. 대폭 수정 예정~~~~~~~

[feat]로그인 전 헤더 생성

---

package-lock.json
package.json
src/assets/styles/comparison.module.css
src/assets/styles/figures.module.css
src/components/common/SideBar/SideBar.js
src/components/common/SideBar/SideBar.module.css
src/components/common/whatSelectBox/WhatRadioButtons.js
src/components/common/whatSelectBox/WhatRadioButtons.module.css
src/components/specific/ControlBox/ControlBox.module.css
src/components/specific/alarmScrollBox/alarmScrollBox.module.css
src/components/specific/charts/LineChartComponent.css
src/components/specific/charts/lineChart.js
src/components/specific/charts/lineChartCompare.js
src/pages/ClassRoom/Comparison.js
src/pages/ClassRoom/Figures.js

[fix] Figures 페이지에서 그래프로 표현하고자 하는 버튼 선택에 따라 그래프가 생성되도록 변경(ex. 온도 버튼, 습도 버튼 등)
오류가 발생할 경우 : npm install react-icons 시도해봐 주세요:)

[fix] 버튼에 따라 그래프 반응형으로 생성되도록 변경

---

src/App.js

feat 관리자페이지 수정

---

src/App.js
src/components/common/SideBar/SideBar.js

feat 링크 설정

---

package-lock.json
src/components/common/Header/Header.js
src/components/common/Header/Login_Header.js

1. scr폴더 내 ../../Header/Header.js 파일 건드렸습니다
2. 로고 클릭시 root로 이동할 수 있는 기능 넣음
3. <Link></Link>로 사용하고 싶었는데 <a>가 함께 딸려와서 logo 크기가 줄어들길래 navigate써서 했습니다
4. 부디 충돌나지 않기를 바라며🤦‍♂️🙏

[feat] 로고 클릭시 root로 이동 기능

---

src/pages/Login/Login.css
src/pages/Login/Login.js
src/pages/SignUp/SignUp.css
src/pages/SignUp/SignUp.js

1. Header_Login 사용 잠정 중단
2. Login과 SignUp 페이지 모두 기존의 Header 사용 예정(추후 변동 가능)
3. 아직도 (너무)못생겨서 수정할거임

[refactor] SignUp, Login 코드 리팩토링

---

src/components/specific/charts/lineChartCompare.js
src/components/specific/comparison/StatusBox/statusBox.js
src/pages/ClassRoom/Comparison.js

[fix] comparison 페이지: 강의실 선택에 따라 그래프의 표시 변경

[fix] comparison 페이지: 강의실 선택에 따라 그래프의 표시 변경

---

src/pages/FloorCheck/FloorCheck.js

층별 강의실 수치 확인 페이지 생성
위치 - src/pages/FloorCheck/FloorCheck.js & src/pages/FloorCheck/FloorCheck.css

[feat] 층별 강의실 페이지

---

src/App.js
src/pages/FloorCheck/FloorCheck.js
src/pages/FloorCheck/FloorCheck.module.css

1. 배치는 했다만 마음에 들지 않음
2. 화면 전체 비율이 쪼그라들음
3. css와 js 간의 조율이 필요...
4. .css 파일을 파일명.css 했더니 적용이 안되는 일 발생, 앞으로는 파일명.module.css로 설정하기로 다짐

[feat] 층별강의실 수치 확인 페이지

---

src/components/common/SideBar/SideBar.js
src/pages/Main.js

1. SideBar에서 층별 수치 보기 누르면 해당 페이지로 이동하도록 설정
2. Main 페이지에서 현재 있는 조감도 누르면 해당 페이지로 이동하도록 설정

[feat] 사이드바, 메인화면 -> 층별 수치 보기

---

src/pages/Main.js

[fix] Main 조감도 사진 크기 수정

---

src/components/common/Header/Header.module.css

1. 기존 사용하던 width: clamp(167px, 99%, 1600px);을 주석처리,
2. margin-left = 1%;에 맞추어 margin-right : 1%; 추가해줌
3. 창 크기 줄어들어도 괜찮은데 문제 있으면 다시 고치세용

[fix] Header 줄 크기 수정

---

src/assets/styles/Contact.module.css
src/pages/Contact/Contact.js

[chore] 관리자 페이지 css수정

---

src/assets/styles/Contact.module.css
src/assets/styles/Manager.module.css
src/components/common/ControlBoxMg/ControlBoxMg.js
src/components/common/ControlBoxMg/ControlBoxMg.module.css
src/components/common/ManageAll/ManageAll.js
src/components/common/ManageAll/ManageAll.module.css
src/pages/Contact/Contact.js
src/pages/Manager/Manager.js

1. 관리자페이지 화면 비율 수정
2. 000관리자 페이지 화면비율수정

[fix] 화면비율수정

---

src/assets/styles/Log.module.css

[fix] 로그 화면 수정

---

src/pages/forecast.js
src/pages/test.js

날씨 api 연동 테스트 실행 확인
-> 기상청 API 사용 
forecast.js: 날씨 정보를 가져오는 작업 수행
test.js: 날씨 정보가 잘 가져와지는 것을 확인한 test 페이지
(/test로 연결 가능)
+체감온도는 찾지 못함

[feat]: 날씨 api 연동 테스트 실행 확인

---

src/pages/Login/Login.js
src/pages/Login/Login.module.css

1. Login.css -> Login.module.css로 이름 바꿈
2. Login.js 일부 수정

[chore] 로그인 페이지 비율 맞춤

---

src/components/common/Header/Header.js
src/pages/FloorCheck/FloorCheck.js
src/pages/FloorCheck/FloorCheck.module.css

1. Header.js 파일 수정
2. FloorCheck.js 및 module.css 수정

[fix] 메인 로고 누를 때 렌더링

---

src/pages/Login/Login.module.css
src/pages/Main.module.css

1. Login.module.css 파일 수정 ->회원가입 하기 hover 하면 주황색으로 변경되는 걸 수정했슴더
2. Main.module.css 파일 수정 ->날씨랑 센서 로그는 hover해도 기능 없게 수정

[fix] 로그인 창에서 간단한 스타일 변경

---

src/pages/Main.js

[fix] 다른 건물 누르면 신공학관 사라지는 오류 해결

---

src/pages/Main.js
src/pages/Main.module.css

1. Main.js 에 preventDefault()로 hover 방지
2. Main.module.css에서 moveLeft:hover내 포인터 이벤트 none으로 설정 => 신공학관은 그 자리에 있을 수 있게 됨 꺄호

[fix] 신공학관 hover시 이동하는 문제 해결

---

src/smartMirror/components/tipsSlide/tipsSlide.js
src/smartMirror/components/tipsSlide/tipsSlide.module.css
src/smartMirror/pages/classRoom.js

[feat] 스마트미러 강의실 페이지 Tips 실제 정보에 따라 변경되도록 수정(슬라이드 형태)
5초마다 자동 변경(슬라이드가 여러 개이면)

[feat] 스마트미러 강의실 페이지 Tips 실제 정보에 따라 변경되도록 수정(슬라이드 형태)

---

src/pages/Main.js
src/pages/Main.module.css
src/pages/SignUp/SignUp.js
src/pages/SignUp/SignUp.module.css

1. Main.js 건물 클릭시 위 문구 삭제
2. 회원가입 시 메일로 알림 받을 건지 여부

[fix] 메인/회원가입 페이지 수정

---

src/pages/SignUp/SignUp.module.css

[fix] 회원가입 창 수정

---

src/smartMirror/components/tipsSlide/tipsSlide.js
src/smartMirror/pages/classRoom.js

[fix] 스마트미러 tips 줄 변경

---

src/pages/Main.js

1. Main.js에서 rain, forecast 등을 불러오며 runtime 에러 발생
2. 조건문 걸어서 해결

[fix] runtime error

---

src/pages/Main.js
src/pages/Main.module.css

[chore] 웹 Main api 연동 취소

---

src/pages/Main.js
src/pages/Main.module.css

1. Main.js 페이지 날씨 API 재연동
2. Main.module.css 디자인 재수정
3. 제발 오류나지 말아라~

[feat] Main페이지 날씨 API 연동

---

package.json
src/assets/styles/Log.module.css
src/pages/Alarm/Alarm.js
src/pages/Log/Log.js

[feat] 알림, 로그 api연결

---

src/pages/FloorCheck/FloorCheck.js
src/pages/FloorCheck/FloorCheck.module.css
src/pages/Main.js

[feat] FloorCheck.js 수정

---

src/pages/Login/Login.js
src/pages/SignUp/SignUp.js
src/pages/SignUp/SignUp.module.css

1. SignUp.js와 .css 수정
2. 이메일 코드는 아직 연동하지 않았음
3. 로그인 Login.js 연동중

[feat] 회원가입 API 연동

---

src/pages/Main.module.css

1. Main.module.css 에서 left:30% -> left:35%로 수정

[fix] Main 도면도 위치 수정

---

src/pages/Login/Login.js
src/pages/Main.js
src/pages/SignUp/SignUp.js
src/pages/SignUp/SignUp.module.css

1. Login.js 수정, API 연동
2. Main.js에서 관리자 이름은 못 가져왔음
3. 차차 수정할 예정

[feat] 로그인 API 연동

---

src/components/common/periodDropdown/periodDropdown.js
src/components/specific/charts/lineChart.js
src/components/specific/charts/lineChartCompare.js
src/components/specific/comparison/StatusBox/statusBox.js
src/pages/ClassRoom/Figures.js

[fix]강의실 수치, 비교 페이지 그래프 연결 api 변경
(기간 설정 api로 변경(betweenDates))

[fix]강의실 수치, 비교 페이지 그래프 연결 api 변경

---

src/pages/FloorCheck/FloorCheck.js
src/pages/FloorCheck/FloorCheck.module.css
src/pages/Log/Log.js
src/pages/Login/Login.js
src/pages/Main.js
src/pages/Main.module.css
src/pages/SignUp/SignUp.js

1. SignUp.js 회원가입 연동 -> json형식이 아닌 textplain
2. Login.js 로그인 연동 -> json 형식
3. Main.js 닉네임 연동 -> json 형식
4. floorcheck.js 수치 나타내는 박스 위치 수정

[feat] 회원가입, 로그인, 메인화면 닉네임 연동

---

src/App.js
src/pages/FloorCheck/FloorCheck.js
src/pages/FloorCheck/FloorCheck.module.css
src/pages/FloorCheck/test2.js
src/pages/Login/Login.js
src/pages/Main.js

1. FloorCheck.js 센서값 API 연동 
1_2. 허나 두 개 강의실일 때 하나만 가져오는 치명적인 오류!!!!
1_3. 차차 고칠 예정 : )
2. 좌표 고치고 애니메이션 추가 
2_2. 1번의 문제가 해결되는 대로 좌표 색도 변할 예정

[feat] 층별수치확인 API 연동(1/2) 및 좌표 옮김

---

src/pages/Main.js

main에서 사진 경로 수정
경로 변화 :
public/Main/ ...  ->  public/src/assets/images/main/(hoverBoxIcons) ...

[fix] 사진 경로 수정

---

src/components/common/SideBar/SideBar.js
src/pages/Main.js

[fix] Main.js 호버 박스 z-index 수정

---

src/pages/Log/Log.js

[fix] 로그 페이지 수정

---

src/components/common/ControlBoxMg/ControlBoxMg.js
src/components/common/ControlBoxMg/ControlBoxMg.module.css
src/components/common/ManageAll/ManageAll.js
src/pages/Main.js

[feat] 수정사항

---

src/pages/Main.js

[fix] Main.js 수정

---

src/pages/FloorCheck/FloorCheck.js

[fix] Floorcheck.js 수정중

---

src/pages/FloorCheck/FloorCheck.js

[fix] floorcheck.js 수정

---

src/pages/Main.js
src/pages/Main.module.css

[refactor] Main.js

---

src/smartMirror/pages/main.js
src/smartMirror/pages/main.module.css

[refactor] 리팩토링 최종

---

src/components/common/Popup/Popup.js
src/components/common/Popup/Popup.module.css

[feat] popup.js 애니메이션 추가

---

src/pages/Main.js
src/pages/Main.module.css

[fix] Main.js

---

src/pages/FloorCheck/FloorCheck.js

[fix] Floorcheck.js
